[project]
name = "imc2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jedi-language-server>=0.44.0",
    "prosperity3bt>=0.4.0",
    "ruff>=0.11.2",
]
